services:
    _defaults:
        autoconfigure: true

    ExAkt\CtmHeader\Controller\:
        resource: ../src/Controller

    ExAkt\CtmHeader\EventListener\:
        resource: ../src/EventListener
        autowire: true
